# Generated by Django 3.1.1 on 2020-10-10 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Breakfast',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('user_name', models.TextField(max_length=10, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('food_names', models.CharField(max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(max_length=20, null=True)),
                ('calories', models.IntegerField(null=True)),
                ('carbs', models.IntegerField(null=True)),
                ('proteins', models.IntegerField(null=True)),
                ('fats', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('user_name', models.TextField(max_length=10, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('food_names', models.CharField(max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(max_length=20, null=True)),
                ('calories', models.IntegerField(null=True)),
                ('carbs', models.IntegerField(null=True)),
                ('proteins', models.IntegerField(null=True)),
                ('fats', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='fitnessmen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField(max_length=10)),
                ('date', models.DateField(auto_now=True)),
                ('Height', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Weight', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('activity', models.CharField(max_length=20, null=True)),
                ('goals', models.CharField(max_length=20, null=True)),
                ('goalweight', models.IntegerField(null=True)),
                ('weekly_goal', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('Abdomen', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Neck', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='fitnesswomen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField(max_length=10, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('Height', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Weight', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('activity', models.CharField(max_length=20, null=True)),
                ('goals', models.CharField(max_length=20, null=True)),
                ('goalweight', models.IntegerField(null=True)),
                ('weekly_goal', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('Hip', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Waist', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Neck', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lunch',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('user_name', models.TextField(max_length=10, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('food_names', models.CharField(max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(max_length=20, null=True)),
                ('calories', models.IntegerField(null=True)),
                ('carbs', models.IntegerField(null=True)),
                ('proteins', models.IntegerField(null=True)),
                ('fats', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Snacks',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('user_name', models.TextField(max_length=10, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('food_names', models.CharField(max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(max_length=20, null=True)),
                ('calories', models.IntegerField(null=True)),
                ('carbs', models.IntegerField(null=True)),
                ('proteins', models.IntegerField(null=True)),
                ('fats', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='userdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField(max_length=10, null=True, unique=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('state', models.CharField(max_length=30, null=True)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=20, null=True)),
                ('food_type', models.CharField(max_length=20, null=True)),
                ('food_preference', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
