# Generated by Django 3.1.1 on 2020-10-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial2'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakfast',
            name='food_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dinner',
            name='food_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lunch',
            name='food_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='snacks',
            name='food_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='breakfast',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='snacks',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
